export const getDatePickerStyles = () => ({
	root: "flex flex-col gap-1",
	label: "text-sm font-medium text-(--color-text)",
	group: [
		"flex items-center border border-(--color-border) rounded px-2 py-1 gap-1",
		"bg-(--color-surface)",
		"data-[focused]:border-(--color-primary)",
		"data-[disabled]:opacity-50 data-[disabled]:cursor-not-allowed",
		"data-[invalid]:border-(--color-danger)",
	].join(" "),
	input: "flex items-center flex-1 gap-0",
	segment: [
		"rounded px-0.5 text-sm text-(--color-text) outline-none",
		"data-[placeholder]:text-(--color-text-muted)",
		"data-[focused]:bg-(--color-primary) data-[focused]:text-(--color-primary-foreground)",
		"data-[type=literal]:text-(--color-text-muted)",
	].join(" "),
	button: [
		"min-h-11 min-w-11 flex items-center justify-center rounded text-(--color-text-muted) outline-none",
		"hover:text-(--color-text)",
		"focus-visible:outline-2 focus-visible:outline-(--color-primary)",
	].join(" "),
	description: "text-sm text-(--color-text-muted)",
	error: "text-sm text-(--color-danger)",
	popover: "z-50 shadow-lg rounded bg-(--color-surface) border border-(--color-border) p-3",
	calendar: "flex flex-col gap-2",
	calendarHeader: "flex items-center justify-between mb-1",
	calendarHeading: "text-sm font-medium text-(--color-text)",
	navButton: [
		"p-1 rounded text-(--color-text-muted) outline-none text-xs",
		"hover:text-(--color-text)",
		"focus-visible:outline-2 focus-visible:outline-(--color-primary)",
	].join(" "),
	grid: "border-collapse w-full",
	cell: [
		"w-8 h-8 text-xs text-center rounded-full cursor-default outline-none flex items-center justify-center",
		"hover:bg-(--color-surface)",
		"data-[today]:font-bold data-[today]:text-(--color-primary)",
		"data-[selected]:bg-(--color-primary) data-[selected]:text-(--color-primary-foreground)",
		"data-[selection-start]:rounded-full data-[selection-end]:rounded-full",
		"data-[outside-month]:opacity-30",
		"data-[disabled]:opacity-30",
		"data-[unavailable]:line-through data-[unavailable]:text-(--color-danger)",
		"focus-visible:outline-2 focus-visible:outline-(--color-primary)",
	].join(" "),
	rangeSeparator: "text-(--color-text-muted) px-1 text-sm",
})
