packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"

ignoredOptionalDependencies:
  - sharp

overrides:
  postcss: ^8.5.23
  minimatch@5: ^10.2.5
  minimatch@9: ^10.2.5
  brace-expansion@5: ^5.0.9
  esbuild@0.18.20: ^0.25.12

allowBuilds:
  cpu-features: true
  esbuild: true
  protobufjs: true
  ssh2: true
