/**
 * The hand-authored half of the baseline migration (ADR-40, Q41).
 *
 * # Why a baseline has a hand-authored half at all
 *
 * `drizzle.config.ts` points at the **control plane** alone, and drizzle-kit emits that
 * perfectly: one copy, one schema, a snapshot to diff the next change against. Three
 * things are outside what it can express, and they are what this module emits:
 *
 *   1. **The per-environment copies.** N copies of one table in N schemas whose names
 *      come from a database row is not a shape a schema diff has. `./sql.ts` emits one
 *      environment from the data-plane module; this module calls it once per shipped
 *      environment.
 *   2. **Triggers and their functions.** Not expressible as Drizzle schema, which is
 *      why migration 0001 was hand-authored too. The functions stay **single, in
 *      `control`**, and the data-plane triggers in every environment execute them.
 *   3. **Roles, grants and revokes.** Migration 0021 established the precedent and the
 *      reason: the migration that creates a table is the only place that runs as its
 *      owner in the same step, so a table's grants belong to it.
 *
 * The emitted text is **checked in** to `migrations/0000_environments_baseline.sql`,
 * because a migration is a file the migrator reads rather than a function it calls.
 * `baseline.test.ts` asserts the checked-in text is still exactly what this module
 * produces, so the two cannot drift: change the data-plane module and the baseline test
 * fails until `pnpm --filter @roonga/qcms-db db:emit-baseline` has been re-run.
 *
 * # There is no `DROP` and no `SET SCHEMA` here, and that is the ruling
 *
 * Nothing is dropped because nothing is moved, and nothing is moved because the
 * baseline creates each table where it belongs the first time (Q41). Every existing
 * database is deleted and recreated by hand; there is no upgrade path and none is
 * written (Q22). `migrations.test.ts` asserts the absence of both keywords across the
 * whole migration tree, so this property is executable rather than a convention.
 */

import { CONTROL_ROLE, CONTROL_SCHEMA, environmentRoleName } from "../schema/schemas.js";

import {
  createEnvironmentStatements,
  grantEnvironmentStatements,
  revokeMigrateOnlyStatement,
} from "./sql.js";

/**
 * The environments a fresh database is created with (Q1).
 *
 * Exactly two, in this order, which is also the order `control.environments.position`
 * records and therefore the canonical order a combined access-group name is written in
 * (Q42; task 069 owns the normalisation and the refusal).
 */
export const SHIPPED_ENVIRONMENTS: readonly string[] = ["test", "prod"];

/** The marker the checked-in baseline puts between the two halves. */
export const HAND_AUTHORED_MARKER =
  "-- ===========================================================================\n" +
  "-- Everything above this line is generated by `drizzle-kit generate` from the\n" +
  "-- CONTROL-PLANE schema module. Everything below is HAND-AUTHORED, because\n" +
  "-- drizzle-kit has no notion of N copies of one table in N schemas whose names\n" +
  "-- come from a database row (ADR-40, Q41). It is emitted by\n" +
  "-- `packages/db/src/environment/baseline.ts` and asserted by `baseline.test.ts`;\n" +
  "-- re-run `pnpm --filter @roonga/qcms-db db:emit-baseline` after changing the\n" +
  "-- data-plane schema module rather than editing the SQL below by hand.\n" +
  "-- ===========================================================================";

/**
 * The trigger functions, single copies in `control`.
 *
 * These are cross-version predicates ("this value may not change") comparing OLD and
 * NEW, which a CHECK cannot express: a CHECK validates a NEW row against a static
 * predicate. Hence `BEFORE` triggers. The two ledger functions are executed by a
 * trigger in **every** environment, which is why they live in `control` rather than
 * being copied per schema: one body, N triggers, and a fix to the body is one edit.
 */
function triggerFunctionStatements(): string[] {
  return [
    `-- The answer ledger is append-only (I5, R3). Any UPDATE is rejected, in every
-- environment. One body in \`control\`, executed by one trigger per \`data_<env>\`.
CREATE FUNCTION ${CONTROL_SCHEMA}.answers_reject_update() RETURNS trigger AS $$
BEGIN
\tRAISE EXCEPTION 'answers are append-only (I5): UPDATE is rejected'
\t\tUSING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;`,
    `-- Scoped DELETE door for the ledger (ADR-17). DELETE is rejected unless the
-- transaction-local guard \`qcms.allow_answer_delete\` is set to 'on', which only the
-- two sanctioned whole-session doors do: \`eraseSession\` and \`purgeExpired\`. SET LOCAL
-- reverts at transaction end, so the door is never left open.
--
-- \`current_setting(..., missing_ok => true)\` returns NULL when the GUC was never set,
-- so \`IS DISTINCT FROM 'on'\` rejects the un-flagged case and permits only 'on'.
CREATE FUNCTION ${CONTROL_SCHEMA}.answers_reject_delete() RETURNS trigger AS $$
BEGIN
\tIF current_setting('qcms.allow_answer_delete', true) IS DISTINCT FROM 'on' THEN
\t\tRAISE EXCEPTION 'answers DELETE is only permitted via the sanctioned erasure/retention path (ADR-17)'
\t\t\tUSING ERRCODE = 'restrict_violation';
\tEND IF;
\tRETURN OLD;
END;
$$ LANGUAGE plpgsql;`,
    `-- Once published, a question version's definition is frozen (I1). Status may still
-- transition and published_at may be set; the definition JSONB may not change.
CREATE FUNCTION ${CONTROL_SCHEMA}.question_versions_freeze_published() RETURNS trigger AS $$
BEGIN
\tIF OLD.status = 'published' AND NEW.definition IS DISTINCT FROM OLD.definition THEN
\t\tRAISE EXCEPTION 'published question_versions.definition is immutable (I1): UPDATE is rejected'
\t\t\tUSING ERRCODE = 'restrict_violation';
\tEND IF;
\tRETURN NEW;
END;
$$ LANGUAGE plpgsql;`,
    `CREATE TRIGGER "question_versions_freeze_published"
\tBEFORE UPDATE ON ${CONTROL_SCHEMA}."question_versions"
\tFOR EACH ROW EXECUTE FUNCTION ${CONTROL_SCHEMA}.question_versions_freeze_published();`,
    `-- Published form versions are immutable (R1, I1). No UPDATE path exists.
CREATE FUNCTION ${CONTROL_SCHEMA}.form_versions_reject_update() RETURNS trigger AS $$
BEGIN
\tRAISE EXCEPTION 'form_versions are immutable (R1, I1): UPDATE is rejected'
\t\tUSING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;`,
    `CREATE TRIGGER "form_versions_reject_update"
\tBEFORE UPDATE ON ${CONTROL_SCHEMA}."form_versions"
\tFOR EACH ROW EXECUTE FUNCTION ${CONTROL_SCHEMA}.form_versions_reject_update();`,
  ];
}

/**
 * The live environment set, seeded with the two a fresh database is created with.
 *
 * `position` is 1-based and is the order Q42's combined set is written in. The command
 * that creates a later environment appends at `max(position) + 1`.
 */
function seedEnvironmentsStatement(): string {
  const values = SHIPPED_ENVIRONMENTS.map(
    (environment, index) => `('${environment}', ${index + 1})`,
  ).join(", ");
  return (
    `-- The live set every per-environment job reads (Q1). A fresh database is created\n` +
    `-- with exactly these two; further rows are written by the environment command.\n` +
    `INSERT INTO ${CONTROL_SCHEMA}."environments" ("name", "position") VALUES ${values};`
  );
}

/**
 * **No role is created here, and that is deliberate.**
 *
 * The task's work order says the baseline creates the three kinds of role for the
 * shipped environments. It cannot, and the two reasons are worth stating so the gap is a
 * recorded decision rather than an omission:
 *
 *   1. **A login role needs a password, and a migration may hold none.** The credential
 *      belongs in the operator's secret store; a migration that carried one would put it
 *      in the published package and in every adopter's git history.
 *   2. **The migrating credential is not allowed to.** `qcms_migrate` is granted schema
 *      ownership and `CREATE` on the database, never `CREATEROLE` (SEC-10), so an
 *      unguarded `CREATE ROLE` would fail the whole migration on exactly the deployment
 *      the split exists for.
 *
 * So the roles stay **the operator's to create**, from the recipe in
 * `docs/operations.md`, before the first migration - which is the ordering the recipe
 * already specifies and `docker-compose.yml` already arranges with its `db-roles`
 * one-shot. What this migration owns is every **grant** and **revoke** on the tables it
 * creates, each guarded on the role existing, which is migration 0021's own rule: the
 * migration that creates a table is the only place that runs as its owner in the same
 * step.
 *
 * The environment **command** does create a role, because it is given a password and
 * runs under the migration credential interactively.
 */

/** The control role's rights on `control`: DML, with `two_factor_resets` carved out. */
function controlRoleGrantStatement(): string {
  const statements = [
    `GRANT USAGE ON SCHEMA "${CONTROL_SCHEMA}" TO "${CONTROL_ROLE}"`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "${CONTROL_SCHEMA}" TO "${CONTROL_ROLE}"`,
    `GRANT USAGE ON ALL SEQUENCES IN SCHEMA "${CONTROL_SCHEMA}" TO "${CONTROL_ROLE}"`,
  ];
  const body = statements.map((statement) => `\t\tEXECUTE '${statement}';`).join("\n");
  return `-- \`qcms_app_control\` serves better-auth, authoring, grants, releases and closes, so
-- it holds DML on the whole of \`control\` - with the audit tables carved out below and
-- in task 069's migration. In the data schemas it holds INSERT on \`outbox\` and nothing
-- else at all (Q49), which the per-environment block above grants.
DO $$
BEGIN
\tIF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${CONTROL_ROLE}') THEN
${body}
\tEND IF;
END
$$;`;
}

/** `public` is left empty, off every search path, with `CREATE` on it granted to nobody. */
function lockPublicStatement(): string {
  return `-- \`public\` holds no QCMS object at all and is on no search path (Q20, criterion 2).
-- PostgreSQL 15 already revokes CREATE on it from PUBLIC; stated here so the property
-- is a thing this migration establishes rather than a default it inherits, and so a
-- database restored onto an older cluster gets it too.
REVOKE CREATE ON SCHEMA "public" FROM PUBLIC;`;
}

/**
 * Every hand-authored statement of the baseline, in dependency order.
 *
 * The order is not cosmetic: the trigger functions exist before any trigger executes
 * them, every environment's tables exist before its grants name them, and the
 * migrate-only revoke runs last so it takes back whatever the passes above handed out.
 */
export function baselineHandAuthoredStatements(
  environments: readonly string[] = SHIPPED_ENVIRONMENTS,
): string[] {
  return [
    lockPublicStatement(),
    ...triggerFunctionStatements(),
    seedEnvironmentsStatement(),
    ...environments.flatMap((environment) => createEnvironmentStatements(environment)),
    controlRoleGrantStatement(),
    ...environments.flatMap((environment) => grantEnvironmentStatements(environment)),
    // Last, so it takes back whatever the DML passes above handed out (Q40, finding B).
    revokeMigrateOnlyStatement(),
  ];
}

/** The hand-authored half as one block, joined the way the migrator splits it. */
export function baselineHandAuthoredSql(
  environments: readonly string[] = SHIPPED_ENVIRONMENTS,
): string {
  const statements = baselineHandAuthoredStatements(environments);
  // The marker rides the first statement rather than standing as one of its own: the
  // migrator executes every breakpoint-separated chunk, and a chunk that is only
  // comments is a statement that does nothing, which is a thing to explain later.
  return [`${HAND_AUTHORED_MARKER}\n${statements[0] ?? ""}`, ...statements.slice(1)].join(
    "\n--> statement-breakpoint\n",
  );
}
