CREATE TABLE "control"."form_releases" (
	"form_id" text NOT NULL,
	"environment" text NOT NULL,
	"version" integer NOT NULL,
	"sequence" integer NOT NULL,
	"from_environment" text,
	"released_by" text NOT NULL,
	"approved_by" text,
	"released_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "form_releases_form_id_environment_sequence_pk" PRIMARY KEY("form_id","environment","sequence"),
	CONSTRAINT "form_releases_version_positive" CHECK ("control"."form_releases"."version" > 0),
	CONSTRAINT "form_releases_sequence_positive" CHECK ("control"."form_releases"."sequence" > 0),
	CONSTRAINT "form_releases_from_other_environment" CHECK ("control"."form_releases"."from_environment" is null or "control"."form_releases"."from_environment" <> "control"."form_releases"."environment")
);
--> statement-breakpoint
ALTER TABLE "control"."form_releases" ADD CONSTRAINT "form_releases_form_version_fk" FOREIGN KEY ("form_id","version") REFERENCES "control"."form_versions"("form_id","version") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "control"."form_releases" ADD CONSTRAINT "form_releases_environment_fk" FOREIGN KEY ("environment") REFERENCES "control"."environments"("name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "control"."form_releases" ADD CONSTRAINT "form_releases_from_environment_fk" FOREIGN KEY ("from_environment") REFERENCES "control"."environments"("name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "form_releases_environment_idx" ON "control"."form_releases" USING btree ("environment","form_id","sequence" DESC NULLS LAST);--> statement-breakpoint
-- ===========================================================================
-- Everything above this line is generated by `drizzle-kit generate` from the
-- CONTROL-PLANE schema module. Everything below is HAND-AUTHORED: triggers are
-- not expressible as Drizzle schema, and a grant belongs to the migration that
-- creates its table (migration 0021's rule), which a schema diff has no notion
-- of. The grants are emitted by `grantControlTableStatements` in
-- `src/environment/sql.ts` and asserted against this file by
-- `src/environment/control-table-grants.test.ts`.
-- ===========================================================================
-- The release history is append-only (ADR-40). It is the audit answer to "what was
-- serving in `prod` on that date, and who put it there", so a row the serving
-- credential can rewrite answers nothing - and rolling back is a NEW row releasing an
-- earlier version, never an edit to the row that recorded the later one (criterion 7).
CREATE FUNCTION control.form_releases_reject_update() RETURNS trigger AS $$
BEGIN
	RAISE EXCEPTION 'form_releases are append-only (ADR-40): UPDATE is rejected'
		USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint
CREATE TRIGGER "form_releases_reject_update"
	BEFORE UPDATE ON control."form_releases"
	FOR EACH ROW EXECUTE FUNCTION control.form_releases_reject_update();
--> statement-breakpoint
-- And no DELETE either, with no sanctioned door beside it. The answer ledger has one
-- (ADR-17's two whole-session paths); this table has none, because a release that was
-- performed is a fact about the deployment rather than personal data, and erasure
-- reaches respondent content and not the operator record of what was serving.
CREATE FUNCTION control.form_releases_reject_delete() RETURNS trigger AS $$
BEGIN
	RAISE EXCEPTION 'form_releases are append-only (ADR-40): DELETE is rejected'
		USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint
CREATE TRIGGER "form_releases_reject_delete"
	BEFORE DELETE ON control."form_releases"
	FOR EACH ROW EXECUTE FUNCTION control.form_releases_reject_delete();
--> statement-breakpoint
-- `qcms_app_control` gets DML, which is what ADR-40's role table gives it on `control`
-- outside the two audit carve-outs; the append-only guard above is what makes the UPDATE
-- and the DELETE fail, exactly as `control.form_versions` already does it. Task 064 set
-- no `ALTER DEFAULT PRIVILEGES` - a default is keyed on (role, schema, object type) and
-- cannot express "every table except the break-glass audit" - so a table created after
-- the baseline arrives with nobody granted on it unless its own migration says so, and
-- the failure is found at runtime rather than by this migration.
DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'qcms_app_control') THEN
		EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "control"."form_releases" TO "qcms_app_control"';
	END IF;
END
$$;
--> statement-breakpoint
DO $$
DECLARE environment_role text;
BEGIN
	FOR environment_role IN
		SELECT 'qcms_app_' || environment.name
			FROM control.environments AS environment
			WHERE EXISTS (
				SELECT 1 FROM pg_roles
				 WHERE rolname = 'qcms_app_' || environment.name)
	LOOP
		EXECUTE format('GRANT SELECT ON "control"."form_releases" TO %I', environment_role);
	END LOOP;
END
$$;
